#!/bin/bash
# Regenerates `gen/sync_git_repo_result.ts` from the JSON schema published in
# scanner-inc/scanner-cli. Run via `yarn gen_schema`.
#
# Requires the `gh` CLI (https://cli.github.com/) to be installed and
# authenticated against an account with read access to the repo.
#
# Override the source ref via $SCANNER_CLI_REF. Default tracks the in-flight
# branch; switch to `main` once that branch merges.
set -euo pipefail

REPO="scanner-inc/scanner-cli"
SCHEMA_PATH="schemas/sync-git-repo-result.schema.json"
REF="${SCANNER_CLI_REF:-swwu/zipball-sync}"

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
mkdir -p "$repo_root/gen"

schema_tmp="$(mktemp)"
trap 'rm -f "$schema_tmp"' EXIT

echo "Downloading $REPO//$SCHEMA_PATH @ $REF ..."
gh api \
  -H "Accept: application/vnd.github.raw" \
  "/repos/$REPO/contents/$SCHEMA_PATH?ref=$REF" \
  > "$schema_tmp"

dst="$repo_root/gen/sync_git_repo_result.ts"

cd "$repo_root"
# `--no-additionalProperties` strips the catch-all `[k: string]: unknown;`
# that json-schema-to-typescript otherwise tacks on every interface — those
# index signatures make downstream type checking useless.
yarn run --silent json2ts \
  --input "$schema_tmp" \
  --no-additionalProperties \
  > "$dst.new"

{
  echo "// AUTOGENERATED — regenerate via \`yarn gen_schema\` (sources the"
  echo "// schema from scanner-inc/scanner-cli)."
  echo ""
  cat "$dst.new"
} > "$dst"
rm "$dst.new"

echo "Wrote $dst"
